apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  # Managed-nodegroup에 설정된 EC2 인스턴스 IAM role을 확인
  role: "upgrade-example-eks-worker-node-role"

  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "upgrade-example"

  securityGroupSelectorTerms:
  - tags:
      aws:eks:cluster-name: "upgrade-example"
      kubernetes.io/cluster/upgrade-example: "owned"
