apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  # karpenter로 노드를 증설하기 위해 replica를 적절히 설정해야 함
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: nginx
        # karpenter로 노드를 증설하기 위해 오버스펙 설정
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 30"]
